export const workCard = [
    {
        project: 'Travel Blogger',
        photo: 'travel-flat.png', 
        description: 'Redefining the travel writing experience',
        colorOne: '#fcfcf5',
        colorTwo: '#f5f7fc',
        colorDirection: 'to bottom right',
        url: 'travel',
    },
    {
        project: 'CubeClock Timer',
        photo: 'timer-preview.png', 
        description: 'Innovative Rubik\'s Cube timer',
        colorOne: '#e3eaff',
        colorTwo: '#edffe3',
        colorDirection: 'to top left',
        url: 'timer',
    },
    {
        project: 'Messaging App',
        photo: 'messaging-preview.png', 
        description: 'Fast, reliable instant messaging',
        colorOne: '#dbffed',
        colorTwo: '#dbf7ff',
        colorDirection: 'to bottom left',
        url: 'messaging',
    },
    {
        project: 'Cinematography Portfolio',
        photo: 'film-preview.png', 
        description: 'Personal portfolio website',
        colorOne: '#fefff7',
        colorTwo: '#faebeb',
        colorDirection: 'to top right',
        url: 'cinematography',
    },
]